GestaoPedidos/custom_users/urls.py
from django.urls import include, path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/docente',views.register_docente, name="register-docente"),
    path('register/funcionario',views.register_funcionario, name="register-funcionario"),
    path('accounts/', include('django.contrib.auth.urls')),
]

GestaoPedidos/pedidos/urls.py
from django.urls import include, path

import pedidosHorario
from . import views

app_name = 'pedidos'
urlpatterns = [
    path('',views.app, name="app"),
    path('lista/',views.index, name="pedidos"),
    path('criar-ano-letivo/',views.criar_ano_letivo, name="criar-ano-letivo"),
    path('ativar-ano-letivo/<int:ano_id>',views.ativar_ano_letivo, name="ativar-ano-letivo"),
    path('editar_ano_letivo/<int:ano_id>',views.editar_ano_letivo, name="editar_ano_letivo"),
    path('eliminar-ano-letivo/<int:ano_id>',views.eliminar_ano_letivo, name="eliminar-ano-letivo"),
    path('listar-ano-letivo/',views.listar_ano_letivo, name="listar-ano-letivo"),
    path('criar-semestre/',views.criar_semestre, name="criar-semestre"),
    path('criar-disciplina/',views.criar_disciplina, name="criar-disciplina"),
    path('estatisticas1/', views.estatisticas1, name="estatisticas1"),
    path('estatisticas2/', views.estatisticas2, name="estatisticas2"),
    path('estatisticas3/', views.estatisticas3, name="estatisticas3"),
    path('pedidos_processados/', views.pedidos_processados, name="pedidos_processados"),
    path('media-pedidos_processados/', views.media_pedidos_processados, name="media_pedidos_processados"),
    path('numero-pedidos_processados/', views.numero_pedidos_processados, name="numero_pedidos_processados"),
    path('pedidos_processados_funcionario/', views.pedidos_processados_funcionario, name="pedidos_processados_funcionario"),
    path('upload-docente/',views.upload_docentes, name="upload-docente"),
    path('import_excel_pandas/', views.import_dsd,name="import_dsd"),
    path('import_sala', views.import_salas, name='import_sala'),
    path('importar_ruc', views.importar_ruc, name='importar_ruc'),
    path('associar_pedido/<int:pedido_id>', views.associar_pedido, name='associar_pedido'),
    path('validar-pedido/<int:pedido_id>', views.validar_pedido, name='validar_pedido'),
    path('rejeitar-pedido/<int:pedido_id>', views.rejeitar_pedido, name='rejeitar_pedido'),
    path('view-pedido/<int:pedido_id>', views.view_pedido, name='view_pedido'),
    path('export-pedidos/', views.export_pedidos_to_excel, name='export_pedidos'),
    path('editar_ano_letivo/<int:ano_id>',views.editar_ano_letivo, name="editar_ano_letivo"),

]

GestaoPedidos/pedidosOutros/urls.py
from django.contrib import admin
from django.urls import path, include
from pedidosOutros import views

app_name = 'pedidosOutros'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.indexOutros, name='pedido_outros'),
    path('criarPedidoOutros/', views.criar_pedido, name='criar_pedido_outros'),
    path('editarPedidoOutros/<int:pedido_id>/', views.editar_pedido, name='editar_pedido_outros'),
    path('eliminarPedidoOutros/<int:id>/', views.eliminarPedidosOutros, name='eliminar_pedido_outros'),
    path('view-pedido/<int:pedido_id>', views.view_pedido, name='view_pedido_outros'),
    path('api-auth', include('rest_framework.urls'))
]

GestaoPedidos/pedidosSala/urls.py
from django.urls import path
from . import views
from rest_framework import routers

app_name = 'pedidosSala'
urlpatterns = [
    path('',views.index, name = "pedido_sala"),
    path('', views.index, name='index'),
    path('criar-pedido/', views.criar_pedido_sala, name='criar_pedido_sala'),
    path('criar-pedido/<int:pedido_id>', views.criar_pedido_sala, name='criar_pedido_sala'),
    path('editar-pedido/<int:pedido_id>', views.editar_pedido_sala, name='editar_pedido_sala'),
    path('eliminar-pedido/<int:pedido_id>', views.eliminar_pedido_sala, name='eliminar_pedido_sala'),
    path('ver_pedido_sala/<int:pedido_id>', views.ver_pedido_sala, name='ver_pedido_sala'),
    path('alterar-estado-pedido/<int:pedido_id>', views.alterar_estado_pedido_sala, name='alterar_estado_pedido_sala'),
    path('sucesso/',views.sucesso, name = "sucesso"),

    # API Functions
    #path('pedidos/', views.pedidos, name = "pedidos"),
    #path('pedidos/<int:pk>/', views.pedido, name = "pedido"),

    # API Classes
    path('pedidos/',  views.PedidoList.as_view(), name = "pedidos"),
    path('pedidos/<int:pk>/',  views.PedidoDetail.as_view(), name = "pedido"),
]

GestaoPedidos/pedidosUC/urls.py
from django.urls import path
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
#router.register('pedidos', test_api)


app_name = 'pedidosUC'
urlpatterns = [
    path('',views.index, name = "pedido_uc"),
    path('criar-pedido/', views.criar_pedido, name='criar_pedido_uc'),
    path('editar-pedido/<int:pedido_id>', views.editar_pedido, name='editar_pedido_uc'),
    path('eliminar-pedido/<int:pedido_id>', views.eliminar_pedido_uc, name='eliminar_pedido_uc'),
    path('view-pedido/<int:pedido_id>', views.view_pedido, name='view_pedido_uc'),
    path('alterar-estado-pedido/<int:pedido_id>', views.alterar_estado_pedido_uc, name='alterar_estado_pedido_uc'),
    path('sucesso/',views.sucesso, name = "sucesso"),
]

GestaoPedidos/urls.py
from django.contrib import admin
from django.urls import path,include
from pedidos import urls as pedidos_urls
from pedidosUC import urls as pedidos_uc_urls
from pedidosHorario import urls as pedidos_horario_urls
from pedidosSala import urls as pedidos_sala_urls
from pedidosOutros import urls as pedidos_outros_urls
from custom_users import urls as users

urlpatterns = [
    path('pedidos/', include(pedidos_urls)),
    path('pedidoHorario/', include(pedidos_horario_urls)),
    path('pedidoUC/', include(pedidos_uc_urls)),
    path('pedidoSala/', include(pedidos_sala_urls)),
    path('pedidoOutros/', include(pedidos_outros_urls)),
    path('users/',include(users)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

GestaoPedidos/pedidos/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.contrib.auth.models import User
from django.db import models
from model_utils.managers import InheritanceManager

from custom_users.models import Docente, Funcionario


class AnoLetivo(models.Model):
    ano = models.CharField(db_column='Ano', max_length=255, blank=True, null=True) 
    datainicio = models.DateField(db_column='DataInicio', blank=True, null=True)
    datafim = models.DateField(db_column='DataFim', blank=True, null=True)
    estado = models.CharField(db_column='Estado', max_length=255, blank=True, null=True) 
    class Meta:
        db_table = 'AnoLetivo'

class Curso(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    curso = models.CharField(db_column='curso', max_length=255, blank=True, null=True)
    codigo = models.IntegerField(db_column='Codigo', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'Curso'


class Semestre(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    inicio_data = models.DateField(db_column='Inicio_Data', blank=True, null=True)  # Field name made lowercase.
    fim_data = models.DateField(db_column='Fim_Data', blank=True, null=True)  # Field name made lowercase.
    nr_horas_service = models.IntegerField(db_column='Nr_Horas_service', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'Semestre'

class Disciplina(models.Model):
    id = models.AutoField(db_column='ID2', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    estado = models.TextField(db_column='Estado')  # Field name made lowercase. This field type is a guess.
    codigodisciplina = models.IntegerField(db_column='codigodisciplina', blank=True, null=True)  # Field name made lowercase.
    semestreid = models.ForeignKey(Semestre, on_delete=models.CASCADE, db_column='SemestreID')  # Field name made lowercase.
    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'Disciplina'

class CursoDisciplina(models.Model):
    cursoid = models.OneToOneField(Curso, on_delete=models.CASCADE, db_column='CursoID', primary_key=True)  # Field name made lowercase.
    disciplinaid2 = models.ForeignKey(Disciplina, on_delete=models.CASCADE, db_column='DisciplinaID2')  # Field name made lowercase.

    class Meta:
        db_table = 'Curso_Disciplina'
        unique_together = (('cursoid', 'disciplinaid2'),)





class Turma(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nturma = models.CharField(db_column='NTurma', max_length=255, blank=True, null=True)  # Field name made lowercase.
    horas_semanais = models.CharField(db_column='Horas_semanais', max_length=255, blank=True, null=True)  # Field name made lowercase.
    horas_periodo = models.CharField(db_column='Horas_periodo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    class Meta:
        db_table = 'Turma'



class Instituicao(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    sigla = models.CharField(db_column='Sigla', max_length=255, blank=True, null=True)
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'Instituicao'


class Edificio(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)
    instituicao = models.ManyToManyField(Instituicao, through='EdificioInstituicao', related_name='edificios')
    localizacao = models.CharField(db_column='Localizacao', max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'Edificio'



class EdificioInstituicao(models.Model):
    edificio = models.ForeignKey(Edificio, on_delete=models.CASCADE)
    instituicao = models.ForeignKey(Instituicao, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Edificio_Instituicao'


class TipoSala(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    tipo = models.CharField(db_column='Tipo', max_length=255, null=False)
    
    class Meta:
        db_table = 'TipoSala'

class Sala(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nsala = models.CharField(db_column='NSala', max_length=255, blank=True, null=True)  # Field name made lowercase.
    lotacao = models.IntegerField(db_column='Lotacao', blank=True, null=True)  # Field name made lowercase.
    tipo_sala = models.ManyToManyField(TipoSala)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)
    edificioid = models.ForeignKey(Edificio, on_delete=models.CASCADE, db_column='EdificioID', null=True)  # Field name made lowercase.
    anoletivo = models.ForeignKey(AnoLetivo, on_delete=models.CASCADE, db_column='AnoLetivo', null=True) # Field name made lowercase.
    
    class Meta:
        db_table = 'Sala'

class Docentes(models.Model):
    # Add any additional fields specific to Docente model here
    codigo = models.IntegerField(db_column='Codigo', blank=True,primary_key=True,default=0)  # Field name made lowercase.
    ativo = models.CharField(db_column='Ativo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    individuo = models.CharField(db_column='Individuo',max_length=255,blank=True, null=True)  # Field name made lowercase.
    data_de_nascimento = models.CharField(db_column='data_de_nascimento', max_length=255,blank=True, null=True)  # Field name made lowercase.
    sexo = models.CharField(db_column='sexo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    tipo_de_identificacao = models.CharField(db_column='tipo_de_Identificacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    identificacao = models.CharField(db_column='identificacao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    data_de_emissao_de_idenficacao = models.CharField(db_column='data_de_emissao_de_idenficacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nacionalidade = models.CharField(db_column='nacionalidade', max_length=255,blank=True, null=True)  # Field name made lowercase.
    arquivo = models.CharField(db_column='arquivo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    data_de_validade_da_identificacao = models.CharField(db_column='data_de_validade_da_identificacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nif = models.CharField(db_column='nif', max_length=255,blank=True, null=True)  # Field name made lowercase.
    pais_fiscal = models.CharField(db_column='pais_fiscal', max_length=255,blank=True, null=True)  # Field name made lowercase.
    digito_verificacao = models.CharField(db_column='digito_verificacao',max_length=255,blank=True, null=True)  # Field name made lowercase. This field type is a guess.

    class Meta:
        db_table = 'docentes'

class Pedido(models.Model):
    objects = InheritanceManager()
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nrpedido = models.IntegerField(db_column='NrPedido', blank=True, null=True)  # Field name made lowercase.
    titulo = models.CharField(db_column='titulo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    dataalvo = models.DateField(db_column='DataAlvo', blank=True, null=True)  # Field name made lowercase.
    dataanalise = models.DateField(db_column='DataAnalise', blank=True, null=True)  # Field name made lowercase.
    datavalidacao = models.DateField(db_column='DataValidacao', blank=True, null=True)  # Field name made lowercase.
    datacriacao = models.DateTimeField(db_column='DataCriacao', auto_now_add=True, blank=True, null=True)  # Field name made lowercase.
    estado = models.CharField(db_column='Estado', max_length=255, blank=True, null=True)  # Field name made lowercase.
    dataalteracao = models.DateTimeField(db_column='DataAlteracao', auto_now=True, blank=True, null=True)  # Field name made lowercase.
    anoletivo = models.ForeignKey(AnoLetivo, on_delete=models.CASCADE, db_column='AnoLetivo', null=True) 
    docente = models.ForeignKey(Docente, on_delete=models.SET_NULL, db_column='Docente', null=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.SET_NULL, db_column='Funcionario', null=True)
    class Meta:
        db_table = 'Pedido'



class Linha(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    uc = models.ForeignKey(Disciplina, on_delete=models.CASCADE, db_column='Disciplina', blank=False)#
    pedidoID = models.ForeignKey(Pedido, on_delete=models.CASCADE, db_column='PedidoID')#


class LinhaOutros(models.Model):

GestaoPedidos/pedidos/forms.py
from django.forms import ModelForm
from django import forms
from .models import AnoLetivo,Semestre,Disciplina
from django.forms import inlineformset_factory


class AnoLetivoForm(forms.ModelForm):
    class Meta:
        model = AnoLetivo
        fields = ['ano','datainicio','datafim']


class SemestreForm(forms.ModelForm):
    class Meta:
        model = Semestre
        fields = ['inicio_data','fim_data','nr_horas_service']


class DisciplinaForm(forms.ModelForm):
    class Meta:
        model = Disciplina
        fields = ['nome','semestreid']


class ExcelUploadForm(forms.Form):
    excel_file = forms.FileField(label='Selecione o ficheiro Excel')

    def clean_excel_file(self):
        excel_file = self.cleaned_data['excel_file']
        if not excel_file.name.endswith('.xlsx'):
            raise forms.ValidationError('Só ficheiros são permitidos Excel (.xlsx)')
        return excel_file

GestaoPedidos/pedidos/templates/estatisticas1.html
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>


{% extends 'app.html' %}
{% load django_tables2 %}
{% load static %}

{% block title %}- Consultar Utilizadores
{% endblock title %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script>
            $(document).ready(function() {
                setTimeout(function() {
                    $('#mensagem').fadeOut('fast');
                }, 5000); // Tempo de exibição em milissegundos
            });
            </script>
            {% if mensagem %}
            <div id="mensagem">
                <div class="mensagem" style="text-align:center; background-color:{{ colorBack }}; color:{{ color }}; padding:20px; display:block;">
                    <h2>{{ mensagem }}</h2>
                </div>
                <br>
            </div>
            {% endif %}
    <div class="columns">
        <div class="column">
            <nav aria-label="breadcrumbs" class="breadcrumb">
                <ul>
                    <li><a href="{% url 'pedidos:app' %}">Início</a></li>
                    <li class="is-active"><a href="">Estatisticas</a>
                    </li>
                </ul>
            </nav>
            <div>
                <div>
                    <h4 style="text-align:center;"><b style="font-size: 30px;">Estatisticas de pedidos processados</b></h4>
                    <hr>
                <form action="{% url 'pedidos:pedidos_processados' %}" method="GET">
                    {% csrf_token %}
                    <div class="control is-clearfix">
                        <label for="id_data_inicio">Data Início:</label>
                        <input name="data_inicio" id="data_inicio" class="input"
                               for="{{ form.dataalvo.value|default_if_none:"" }}" type="date">
                        <label for="id_data_fim">Data Fim:</label>
                        <input name="data_fim" id="data_fim" class="input"
                               for="{{ form.dataalvo.value|default_if_none:"" }}" type="date">
                    </div>
                    <div class="field">
                            <br>
                            <label for="id_estado">Tipo de Pedido:</label>
                            <select class="button is-outlined" name="tipopedido" id="tipopedido">
                                <option value="todos" >Todos</option>
                                <option value="PedidoHorario" {% if 'PedidoHorario' in tipopedido %}selected{% endif %}>Pedido de Horario</option>
                                <option value="PedidoSala" {% if 'PedidoSala' in tipopedido %}selected{% endif %}>Pedido de Sala</option>
                                <option value="PedidoUC" {% if 'PedidoUC' in tipopedido %}selected{% endif %}>Pedido de UC</option>
                                <option value="PedidoOutros" {% if 'PedidoOutros' in tipopedido %}selected{% endif %}>Outros Pedidos</option>
                            </select>
                    </div>
                        <button class="button is-outlined" type="submit">Mostrar</button>

                    </form>
                {% if image_data %}
                    <img src="data:image/png;base64,{{ image_data }}" />
                {% else %}
                    <p style="font-size: 30px;">Sem informação por enquanto.</p>
                {% endif %}
                    <br>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

<script>
  $(function() {
    $("#data_inicio").datepicker();
    $("#data_fim").datepicker();
  });
</script>

GestaoPedidos/pedidos/templates/import_excel_db.html
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>


{% extends 'app.html' %}
{% load django_tables2 %}
{% load static %}

{% block title %}- Consultar Utilizadores
{% endblock title %}

{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
    $(document).ready(function() {
        setTimeout(function() {
            $('#mensagem').fadeOut('fast');
        }, 5000); // Tempo de exibição em milissegundos
    });
    </script>
    {% if mensagem %}
    <div id="mensagem">
        <div class="mensagem" style="text-align:center; background-color:{{ colorBack }}; color:{{ color }}; padding:20px; display:block;">
            <h2>{{ mensagem }}</h2>
        </div>
        <br>
    </div>
    {% endif %}
    <div class="columns">
        <div class="column">
            <nav aria-label="breadcrumbs" class="breadcrumb">
                <ul>
                    <li><a href="{% url 'pedidos:app' %}">Início</a></li>
                    <li class="is-active"><a href="">Importar DSD</a>
                    </li>
                </ul>
            </nav>
            <div>
                <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                <h2>Escolhe os dados para importar:</h2> <br>
                <div class="clearfix"></div>
                </div>
                <div class="x_content">
                <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                </div>
                    <input type="file" name="myfile" class="form-control" required>
                    <button type="submit" class="btn btn-success" >Upload File</button>
                </div>
            </div>
            </div>
        </div>
        </form>
        </div>
    </div>
{% endblock content %}

<script>
  $(function() {
    $("#data_inicio").datepicker();
    $("#data_fim").datepicker();
  });
</script>

GestaoPedidos/pedidos/templates/index_anos_tabela.html
{% extends 'bulma_table_details_anos.html' %}

{% block details_content %}

<table>
    <tbody style="table-layout: fixed;">
        {% for l in row.record.linha_set.all %}
            <tr>
                <td style="width:25%">{{l.anoinicio}}</td>
                <td style="width:25%">{{l.anofim}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock details_content %}

GestaoPedidos/pedidos/templates/navbar.html
{% load static %}

<nav id="main-navbar" class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
      <a class="navbar-item logo" href="{% url 'pedidos:app' %}">
        <img src="{% static '/img/logo.png' %}" alt="Gestão Pedidos">
      </a>

      <a role="button" class="navbar-burger burger" onclick="onclick_burger(event)" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
      </a>
  </div>

  <div class="navbar-menu">
    <div class="navbar-start">

        <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Pedidos</a>

            <div class="navbar-dropdown">
                  <a href="{% url 'pedidos:pedidos' %}" class="navbar-item">Pedidos</a>
                  <a href="{% url 'pedidosHorario:pedido_horario' %}" class="navbar-item">Pedidos de Horário</a>
                  <a href="{% url 'pedidosSala:pedido_sala' %}" class="navbar-item">Pedidos de Sala</a>
                  <a href="{% url 'pedidosUC:pedido_uc' %}" class="navbar-item">Pedidos de Unidade Curricular</a>
                  <a href="{% url 'pedidosOutros:pedido_outros' %}" class="navbar-item">Pedidos Outros</a>
            </div>
      </div>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Importar</a>

          <div class="navbar-dropdown">
                <a href="{% url 'pedidos:import_dsd' %}" class="navbar-item">Importar DSD</a>
                <a href="{% url 'pedidos:import_sala' %}" class="navbar-item">Importar Salas</a>
                <a href="{% url 'pedidos:importar_ruc' %}" class="navbar-item">Importar RUC</a>
                <a href="{% url 'pedidos:upload-docente' %}" class="navbar-item">Importar Docentes</a>

          </div>
        </div>

        {% if user.is_authenticated %}
              {% if user.is_funcionario %}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Estatísticas</a>

          <div class="navbar-dropdown">
                  <a href="{% url 'pedidos:estatisticas1' %}" class="navbar-item">Estatisticas de pedidos processados</a>
                  <a href="{% url 'pedidos:estatisticas2' %}" class="navbar-item">Estatisticas de média de tempo de processamento de um tipo de pedido</a>
                  <a href="{% url 'pedidos:estatisticas3' %}" class="navbar-item">Estatisticas de número de pedidos processados de um tipo de pedido, por si</a>
          </div>
        </div>
        {% endif %}
            {% endif %}

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Definições</a>
          
          <div class="navbar-dropdown">
                <a href="{% url 'pedidos:criar-ano-letivo' %}" class="navbar-item">Criar ano letivo</a>
                <a href="{% url 'pedidos:listar-ano-letivo' %}" class="navbar-item">Listar anos letivos</a>
                <a href="{% url 'pedidos:criar-semestre' %}" class="navbar-item">Criar semestre</a>
                <a href="{% url 'pedidos:criar-disciplina' %}" class="navbar-item">Criar disciplina</a>

          </div>
        </div>
    </div>
  </div>

  <div class="navbar-end">
    {% if user.is_authenticated %}
          <div class="navbar-item">Olá {{ user.get_username }}</div>
          <div class="navbar-item"><a href="{% url 'users:logout' %}?next={{ request.path }}">Logout</a></div>
          {% else %}
          <div class="navbar-item"><a href="{% url 'users:login' %}?next={{ request.path }}">Login</a></div>
          {% endif %}

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Registar</a>
            <div class="navbar-dropdown">
              <a href="{% url 'users:register-docente' %}?next={{ request.path }}">Docente</a>
              <a href="{% url 'users:register-funcionario' %}?next={{ request.path }}">Funcionario</a>
            </div>
          </div>

  </div>

</nav>


{% block scripts %}
<script>

</script>

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>

<script>
  $('#dropdown_definicoes').click(function (e) {
    $('#mensagens-dropdown').removeClass('is-active');
  })

  $('#mensagens-dropdown').click(function (e) {
    $('#dropdown_definicoes').removeClass('is-active');
  })

  function onclick_burger(e) {
    $('#main-navbar > .navbar-menu').toggleClass('is-active');
    $('#dropdown_definicoes').toggleClass('is-right');
    $('#dropdown_definicoes').toggleClass('is-left');
    $('#mensagens-dropdown').toggleClass('is-right');
    $('#mensagens-dropdown').toggleClass('is-left');
  };
</script>

{% endblock scripts %}