GestaoPedidos/pedidos/urls.py
from django.urls import include, path

import pedidosHorario
from . import views

app_name = 'pedidos'
urlpatterns = [
    path('',views.app, name="app"),
    path('lista/',views.index, name="pedidos"),
    path('criar-ano-letivo/',views.criar_ano_letivo, name="criar-ano-letivo"),
    path('ativar-ano-letivo/<int:ano_id>',views.ativar_ano_letivo, name="ativar-ano-letivo"),
    path('editar_ano_letivo/<int:ano_id>',views.editar_ano_letivo, name="editar_ano_letivo"),
    path('eliminar-ano-letivo/<int:ano_id>',views.eliminar_ano_letivo, name="eliminar-ano-letivo"),
    path('listar-ano-letivo/',views.listar_ano_letivo, name="listar-ano-letivo"),
    path('criar-semestre/',views.criar_semestre, name="criar-semestre"),
    path('criar-disciplina/',views.criar_disciplina, name="criar-disciplina"),
    path('estatisticas1/', views.estatisticas1, name="estatisticas1"),
    path('estatisticas2/', views.estatisticas2, name="estatisticas2"),
    path('estatisticas3/', views.estatisticas3, name="estatisticas3"),
    path('pedidos_processados/', views.pedidos_processados, name="pedidos_processados"),
    path('media-pedidos_processados/', views.media_pedidos_processados, name="media_pedidos_processados"),
    path('numero-pedidos_processados/', views.numero_pedidos_processados, name="numero_pedidos_processados"),
    path('pedidos_processados_funcionario/', views.pedidos_processados_funcionario, name="pedidos_processados_funcionario"),
    path('upload-docente/',views.upload_docentes, name="upload-docente"),
    path('import_excel_pandas/', views.import_dsd,name="import_dsd"),
    path('import_sala', views.import_salas, name='import_sala'),
    path('importar_ruc', views.importar_ruc, name='importar_ruc'),
    path('associar_pedido/<int:pedido_id>', views.associar_pedido, name='associar_pedido'),
    path('validar-pedido/<int:pedido_id>', views.validar_pedido, name='validar_pedido'),
    path('rejeitar-pedido/<int:pedido_id>', views.rejeitar_pedido, name='rejeitar_pedido'),
    path('view-pedido/<int:pedido_id>', views.view_pedido, name='view_pedido'),
    path('export-pedidos/', views.export_pedidos_to_excel, name='export_pedidos'),
    path('editar_ano_letivo/<int:ano_id>',views.editar_ano_letivo, name="editar_ano_letivo"),

]

GestaoPedidos/pedidosSala/urls.py
from django.urls import path
from . import views
from rest_framework import routers

app_name = 'pedidosSala'
urlpatterns = [
    path('',views.index, name = "pedido_sala"),
    path('', views.index, name='index'),
    path('criar-pedido/', views.criar_pedido_sala, name='criar_pedido_sala'),
    path('criar-pedido/<int:pedido_id>', views.criar_pedido_sala, name='criar_pedido_sala'),
    path('editar-pedido/<int:pedido_id>', views.editar_pedido_sala, name='editar_pedido_sala'),
    path('eliminar-pedido/<int:pedido_id>', views.eliminar_pedido_sala, name='eliminar_pedido_sala'),
    path('ver_pedido_sala/<int:pedido_id>', views.ver_pedido_sala, name='ver_pedido_sala'),
    path('alterar-estado-pedido/<int:pedido_id>', views.alterar_estado_pedido_sala, name='alterar_estado_pedido_sala'),
    path('sucesso/',views.sucesso, name = "sucesso"),

    # API Functions
    #path('pedidos/', views.pedidos, name = "pedidos"),
    #path('pedidos/<int:pk>/', views.pedido, name = "pedido"),

    # API Classes
    path('pedidos/',  views.PedidoList.as_view(), name = "pedidos"),
    path('pedidos/<int:pk>/',  views.PedidoDetail.as_view(), name = "pedido"),
]

GestaoPedidos/pedidosUC/urls.py
from django.urls import path
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
#router.register('pedidos', test_api)


app_name = 'pedidosUC'
urlpatterns = [
    path('',views.index, name = "pedido_uc"),
    path('criar-pedido/', views.criar_pedido, name='criar_pedido_uc'),
    path('editar-pedido/<int:pedido_id>', views.editar_pedido, name='editar_pedido_uc'),
    path('eliminar-pedido/<int:pedido_id>', views.eliminar_pedido_uc, name='eliminar_pedido_uc'),
    path('view-pedido/<int:pedido_id>', views.view_pedido, name='view_pedido_uc'),
    path('alterar-estado-pedido/<int:pedido_id>', views.alterar_estado_pedido_uc, name='alterar_estado_pedido_uc'),
    path('sucesso/',views.sucesso, name = "sucesso"),
]

GestaoPedidos/urls.py
from django.contrib import admin
from django.urls import path,include
from pedidos import urls as pedidos_urls
from pedidosUC import urls as pedidos_uc_urls
from pedidosHorario import urls as pedidos_horario_urls
from pedidosSala import urls as pedidos_sala_urls
from pedidosOutros import urls as pedidos_outros_urls
from custom_users import urls as users

urlpatterns = [
    path('pedidos/', include(pedidos_urls)),
    path('pedidoHorario/', include(pedidos_horario_urls)),
    path('pedidoUC/', include(pedidos_uc_urls)),
    path('pedidoSala/', include(pedidos_sala_urls)),
    path('pedidoOutros/', include(pedidos_outros_urls)),
    path('users/',include(users)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

GestaoPedidos/pedidos/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.contrib.auth.models import User
from django.db import models
from model_utils.managers import InheritanceManager

from custom_users.models import Docente, Funcionario


class AnoLetivo(models.Model):
    ano = models.CharField(db_column='Ano', max_length=255, blank=True, null=True) 
    datainicio = models.DateField(db_column='DataInicio', blank=True, null=True)
    datafim = models.DateField(db_column='DataFim', blank=True, null=True)
    estado = models.CharField(db_column='Estado', max_length=255, blank=True, null=True) 
    class Meta:
        db_table = 'AnoLetivo'

class Curso(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    curso = models.CharField(db_column='curso', max_length=255, blank=True, null=True)
    codigo = models.IntegerField(db_column='Codigo', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'Curso'


class Semestre(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    inicio_data = models.DateField(db_column='Inicio_Data', blank=True, null=True)  # Field name made lowercase.
    fim_data = models.DateField(db_column='Fim_Data', blank=True, null=True)  # Field name made lowercase.
    nr_horas_service = models.IntegerField(db_column='Nr_Horas_service', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'Semestre'

class Disciplina(models.Model):
    id = models.AutoField(db_column='ID2', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    estado = models.TextField(db_column='Estado')  # Field name made lowercase. This field type is a guess.
    codigodisciplina = models.IntegerField(db_column='codigodisciplina', blank=True, null=True)  # Field name made lowercase.
    semestreid = models.ForeignKey(Semestre, on_delete=models.CASCADE, db_column='SemestreID')  # Field name made lowercase.
    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'Disciplina'

class CursoDisciplina(models.Model):
    cursoid = models.OneToOneField(Curso, on_delete=models.CASCADE, db_column='CursoID', primary_key=True)  # Field name made lowercase.
    disciplinaid2 = models.ForeignKey(Disciplina, on_delete=models.CASCADE, db_column='DisciplinaID2')  # Field name made lowercase.

    class Meta:
        db_table = 'Curso_Disciplina'
        unique_together = (('cursoid', 'disciplinaid2'),)





class Turma(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nturma = models.CharField(db_column='NTurma', max_length=255, blank=True, null=True)  # Field name made lowercase.
    horas_semanais = models.CharField(db_column='Horas_semanais', max_length=255, blank=True, null=True)  # Field name made lowercase.
    horas_periodo = models.CharField(db_column='Horas_periodo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    class Meta:
        db_table = 'Turma'



class Instituicao(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    sigla = models.CharField(db_column='Sigla', max_length=255, blank=True, null=True)
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'Instituicao'


class Edificio(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)
    instituicao = models.ManyToManyField(Instituicao, through='EdificioInstituicao', related_name='edificios')
    localizacao = models.CharField(db_column='Localizacao', max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'Edificio'



class EdificioInstituicao(models.Model):
    edificio = models.ForeignKey(Edificio, on_delete=models.CASCADE)
    instituicao = models.ForeignKey(Instituicao, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Edificio_Instituicao'


class TipoSala(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    tipo = models.CharField(db_column='Tipo', max_length=255, null=False)
    
    class Meta:
        db_table = 'TipoSala'

class Sala(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nsala = models.CharField(db_column='NSala', max_length=255, blank=True, null=True)  # Field name made lowercase.
    lotacao = models.IntegerField(db_column='Lotacao', blank=True, null=True)  # Field name made lowercase.
    tipo_sala = models.ManyToManyField(TipoSala)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)
    edificioid = models.ForeignKey(Edificio, on_delete=models.CASCADE, db_column='EdificioID', null=True)  # Field name made lowercase.
    anoletivo = models.ForeignKey(AnoLetivo, on_delete=models.CASCADE, db_column='AnoLetivo', null=True) # Field name made lowercase.
    
    class Meta:
        db_table = 'Sala'

class Docentes(models.Model):
    # Add any additional fields specific to Docente model here
    codigo = models.IntegerField(db_column='Codigo', blank=True,primary_key=True,default=0)  # Field name made lowercase.
    ativo = models.CharField(db_column='Ativo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    individuo = models.CharField(db_column='Individuo',max_length=255,blank=True, null=True)  # Field name made lowercase.
    data_de_nascimento = models.CharField(db_column='data_de_nascimento', max_length=255,blank=True, null=True)  # Field name made lowercase.
    sexo = models.CharField(db_column='sexo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    tipo_de_identificacao = models.CharField(db_column='tipo_de_Identificacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    identificacao = models.CharField(db_column='identificacao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    data_de_emissao_de_idenficacao = models.CharField(db_column='data_de_emissao_de_idenficacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nacionalidade = models.CharField(db_column='nacionalidade', max_length=255,blank=True, null=True)  # Field name made lowercase.
    arquivo = models.CharField(db_column='arquivo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    data_de_validade_da_identificacao = models.CharField(db_column='data_de_validade_da_identificacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nif = models.CharField(db_column='nif', max_length=255,blank=True, null=True)  # Field name made lowercase.
    pais_fiscal = models.CharField(db_column='pais_fiscal', max_length=255,blank=True, null=True)  # Field name made lowercase.
    digito_verificacao = models.CharField(db_column='digito_verificacao',max_length=255,blank=True, null=True)  # Field name made lowercase. This field type is a guess.

    class Meta:
        db_table = 'docentes'

class Pedido(models.Model):
    objects = InheritanceManager()
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nrpedido = models.IntegerField(db_column='NrPedido', blank=True, null=True)  # Field name made lowercase.
    titulo = models.CharField(db_column='titulo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    dataalvo = models.DateField(db_column='DataAlvo', blank=True, null=True)  # Field name made lowercase.
    dataanalise = models.DateField(db_column='DataAnalise', blank=True, null=True)  # Field name made lowercase.
    datavalidacao = models.DateField(db_column='DataValidacao', blank=True, null=True)  # Field name made lowercase.
    datacriacao = models.DateTimeField(db_column='DataCriacao', auto_now_add=True, blank=True, null=True)  # Field name made lowercase.
    estado = models.CharField(db_column='Estado', max_length=255, blank=True, null=True)  # Field name made lowercase.
    dataalteracao = models.DateTimeField(db_column='DataAlteracao', auto_now=True, blank=True, null=True)  # Field name made lowercase.
    anoletivo = models.ForeignKey(AnoLetivo, on_delete=models.CASCADE, db_column='AnoLetivo', null=True) 
    docente = models.ForeignKey(Docente, on_delete=models.SET_NULL, db_column='Docente', null=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.SET_NULL, db_column='Funcionario', null=True)
    class Meta:
        db_table = 'Pedido'



class Linha(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    uc = models.ForeignKey(Disciplina, on_delete=models.CASCADE, db_column='Disciplina', blank=False)#
    pedidoID = models.ForeignKey(Pedido, on_delete=models.CASCADE, db_column='PedidoID')#


class LinhaOutros(models.Model):

GestaoPedidos/pedidosSala/models.py
from django.db import models
from pedidos.models import *
# Create your models here.

class PedidoSala(Pedido):
    #tipopedido = models.ForeignKey(TipoPedido, on_delete=models.CASCADE, db_column='tipoPedidoID')  # Field name made lowercase.

    class Meta:
        db_table = 'PedidoSala'

GestaoPedidos/pedidosSala/forms.py
from django.forms import ModelForm
from django import forms
from .models import PedidoSala
from pedidos.models import LinhaSala
from django.forms import inlineformset_factory


class PedidosSalaForm(forms.ModelForm):
    class Meta:
        model = PedidoSala
        fields = ['titulo','descricao','dataalvo','anoletivo']

class LinhaForm(forms.ModelForm):
    class Meta:
        model = LinhaSala
        fields = ['detalhe','sala', 'horainicio', 'horafim', 'horainicioantigo', 'horafimantigo', 'tipopedido', 'categoriatemporal']


LinhaFormSet = inlineformset_factory(
    PedidoSala, LinhaSala,fields=['detalhe','sala', 'horainicio', 'horafim', 'horainicioantigo', 'horafimantigo', 'tipopedido', 'categoriatemporal'],extra=1
)

GestaoPedidos/pedidosSala/templates/pedidosSala/bulma_table_details.html
{% extends 'pedidosSala/bulma_table.html' %}

{% block table_class %}is-hoverable{% endblock table_class %}



{% block scripts %}
<script>
    $('.main-table > tbody > tr:not(.detail)').click(function (e) {
        $('.main-table > tbody > tr.detail').not($(this).next()).removeClass('is-active');
        $('.main-table > tbody > tr:not(.detail)').not($(this)).find('td.chevron-cell .icon').removeClass('is-expanded');
        $(this).next().toggleClass('is-active');
        $(this).find('td.chevron-cell .icon').toggleClass('is-expanded');
    })
</script>
{% endblock scripts %}

{% block style %}
<style>
    .main-table > tbody > tr:not(.detail) {
        cursor: pointer;
    }

    .main-table > tbody > tr.detail {
        box-shadow: inset 0 1px 3px #dbdbdb;
        background: #fafafa;
        background-color: rgb(250, 250, 250);
    }

    .main-table > tbody > tr.detail .detail-container {
        padding: 1rem;
    }

    .main-table > tbody > tr.detail:hover {
        background-color: #fafafa !important;
    }

    .main-table > tbody > tr.detail:not(.is-active) {
        display: none;
    }

    .main-table > tbody > tr.detail .is-active {
        display: block;
    }

    .icon.is-expanded {
        transform: rotate(90deg);
    }

    .icon {
        transition: transform 150ms ease-out, opacity 86ms ease-out;
    }
</style>
{% endblock style %}

GestaoPedidos/pedidosSala/templates/pedidosSala/criar_linha_pedido_sala.html
{% extends 'app.html' %}

{% block title %}- Formulario{% endblock title %}

{% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        <!-- inside form  
        {{ form.management_form }}
        {% for f in form %}
            {{ f }}
            <hr>
        {% endfor %}
        <input type="Submit" name="Submit" value="Submit"/>
        --> 
    </form>
        
    <form action="" method="POST">
        {% csrf_token %}
        <!-- inside form -->
        <div style="padding: 1rem 2vw 0px;">
            <hr>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <div class="control is-clearfix">
                            <label class="label">Título</label>
                            <input name="titulo" id="titulo" class="input"
                            for="{{ form.titulo.value|default_if_none:"" }}" type="text" maxlength="255">
                        </div>
                        <br>
                        <div class="control is-clearfix">
                            <label class="label">Descrição</label>
                            <textarea for="{{ form.descricao.value|default_if_none:"" }}" style="resize: none;" rows="4" cols="50" name="descricao" id="descricao" class="textarea"> </textarea>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <!-- inside form -->

            <!-- buttons -->
            <div style="margin-top:2%;text-align:center;position:center;">
                <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%"
                        onclick="voltar()">Voltar
                </button>
                <button type="submit" class="button is-success is-outlined" name="Submit">
                    <span>Confirmar</span>
                </button>
            </div>
            <!-- buttons -->
        </div>
    </form>

    </div>

{% endblock content %}


{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        function voltar() {
            location.href = "/pedidoOutros"
        }
    </script>


}
{% endblock scripts %}

GestaoPedidos/pedidosSala/templates/pedidosSala/indexSala.html
{% extends 'app.html' %}
{% load django_tables2 %}
{% load static %}

{% block title %}- Consultar Utilizadores
{% endblock title %}

{% block content %}
{% if mensagem %}
<div style="text-align:center; background-color:{{ colorBack }}; color:{{ color }}; padding:20px;">
    <h2>{{ mensagem }}</h2>
</div>
<br>
{% endif %}
    <div class="columns">
        <div class="column is-3">

            <div class="menu">
                <div class="menu-label">
                    Filtros Pedidos de Sala
                </div>
                <form action="{% url 'pedidosSala:index' %}" method="GET">
                    <ul class="menu-list">
                        <li>
                            <div class="field">
                                <div class="control has-icons-left">
                                    <input class="input" name="pesquisa"
                                           value="{{ filter.form.nome.value|default_if_none:'' }}" type="text"
                                           placeholder="Informação">
                                    <span class="icon is-left">
                                    <i class="mdi mdi-magnify mdi-24px"></i>
                                </span>
                                </div>
                            </div>
                            <div class="field">
                                <label>Tipos:<br>
                                    <br>
                                    <input type="checkbox" name="opcao" value="Titulo" {% if 'Titulo' in opcao %}checked{% endif %} > Titulo <br>
                                    <input type="checkbox" name="opcao" value="Descricao" {% if 'Descricao' in opcao %}checked{% endif %} > Descrição <br>
                                    <input type="checkbox" name="opcao" value="ID" {% if 'ID' in opcao %}checked{% endif %} > ID <br>
                                </label>
                            </div>
                            <div class="field">
                                <label for="id_estado">Estado:</label><br>
                                <select name="id_estado" id="id_estado" class="button is-info">
                                    <option value="todos" >Todos</option>
                                    <option value="espera" {% if 'espera' in id_estado %}selected{% endif %}>Espera</option>
                                    <option value="analise" {% if 'analise' in id_estado %}selected{% endif %}>Análise</option>
                                    <option value="validado" {% if 'validado' in id_estado %}selected{% endif %}>Validado</option>
                                    <option value="recusado" {% if 'recusado' in id_estado %}selected{% endif %}>Recusado</option>
                                </select>
                            </div>
                            <div class="field">
                                {% comment %} <label>Tipos: {% endcomment %}
                                    <br>
                                    {% comment %} Titulo <input type="checkbox" name="opcao" value="Titulo">
                                    Descrição <input type="checkbox" name="opcao" value="Descricao">
                                    Estado <input type="checkbox" name="opcao" value="Estado"> {% endcomment %}
                                    Ano Letivo<input type="checkbox" name="opcao" value="AnoLetivo">
                                {% comment %} </label> {% endcomment %}
                            </div>
                        </li>
                        <br>
                    </ul>
                    <div class="field is-grouped">
                        <p class="control is-expanded">
                            <input class="button is-light is-fullwidth" type="reset"
                                   onclick="event.preventDefault(); window.location='{% url 'pedidosSala:pedido_sala' %}';"
                                   value="Limpar">
                        </p>
                        <p class="control is-expanded">
                            <button class="button is-primary is-fullwidth" type="submit">
                            <span class="icon">
                                <i class="mdi mdi-magnify"></i>
                            </span>
                                <span>Pesquisar</span>
                            </button>
                        </p>
                    </div>
                </form>
            </div>
        </div>
        <div class="column">
            <nav aria-label="breadcrumbs" class="breadcrumb">
                <ul>
                    <li><a href="{% url 'pedidos:app' %}">Início</a></li>
                    <li class="is-active"><a href="">Pedidos de Sala</a>
                    </li>
                </ul>
            </nav>
            <a href="{% url 'pedidosSala:criar_pedido_sala' %}">
                <button type="button" class="button is-success is-outlined" style="margin-bottom: 1rem;"><span
                        class="icon is-small"><i class="mdi mdi-plus"></i></span> <span>Criar Pedidos de Sala</span>
                </button>
            </a>
            <!--

            <ul>
                {% for pedido in pedidos %}
                    <li>{{ pedido.titulo }} <a href="{% url 'pedidosUC:eliminar_pedido_uc' pedido.id %}">Delete</a> <a href="{% url 'pedidosUC:editar_pedido_uc' pedido.id %}">Edit</a></li>
                {% endfor %}
                {% render_table table 'django_tables2/semantic.html' %}
            </ul> -->
            {% render_table table %}

        </div>
    </div>
{% endblock content %}

GestaoPedidos/pedidosSala/templates/pedidosSala/index_sala_tabela.html
{% extends 'pedidosSala/bulma_table_details.html' %}

{% block details_content %}

<table>
    <tbody style="table-layout: fixed;">
        {% for l in row.record.linha_set.all %}
            <tr>
                <td style="width:25%">{{l.titulo}}</td>
                <td style="width:25%">{{l.descricao}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock details_content %}

GestaoPedidos/pedidosSala/templates/pedidosSala/success.html
{% extends 'app.html' %}
{% load django_tables2 %}
{% load static %}

{% block title %}- Consultar Utilizadores
{% endblock title %}

{% block content %}
<div style="text-align:center; background-color:#d4edda; color:#155724; padding:20px; font-size:3em;">
    <div class="columns">
        <div class="column">
            <nav aria-label="breadcrumbs" class="breadcrumb">
                <ul>
                    <li><a href="{% url 'pedido_outros' %}">Início</a></li>
                    <li class="is-active"><a href="">Pedidos de Sala</a>
                    </li>
                </ul>
            </nav>
            <br><br><br><p>Pedido efetuado com sucesso!</p><br><br><br><br>
        </div>

    </div>
</div>
{% endblock content %}

<style>
		body {
			background-color: #f5f5f5;
		}
</style>

GestaoPedidos/pedidosSala/templates/pedidosSala/ver_pedido_sala.html
{% extends 'app.html' %}
{% block title %}- Formulario{% endblock title %}
{%block content %}

<head>
    <meta charset="UTF-8" />
    <title>Dynamic Inline Formsets with Vue.js CDN</title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>
<body>
    <div id="app">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <div style="padding: 1rem 2vw 0px">
                <hr>
                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Título do pedido</label>
                            <div class="control is-clearfix">
                                {{titulo}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Descricao do pedido</label>
                            <div class="control is-clearfix">
                                {{descricao}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Data alvo</label>
                            <div class="control is-clearfix">
                                {{ dataalvo }}
                            </div>
                        </div>
                    </div>
                </div>
                <hr />
            </div>
            <div>
                {% for linha in linhas_data %}
                    <label class="label" for="{{ form.id_for_label }}">Detalhe:</label>
                    {{ linha.detalhe }}

                    <label class="label" for="{{ linha.id_for_label }}">Sala:</label>
                    {{linha.sala.nsala}}

                    <label class="label" for="{{ linha.id_for_label }}">Hora de Início:</label>
                    {{ linha.horainicio }}
                    
                    <label class="label" for="{{ linha.id_for_label }}">Hora de Fim:</label>
                    {{ linha.horafim }}

                    {% if linha.horafimantigo is not None %}
                        <label class="label" for="{{ linha.id_for_label }}">Hora de Início Antiga:</label>
                        {{ linha.horainicioantigo }}
                        
                        <label class="label" for="{{ linha.id_for_label }}">Hora de Fim Antiga:</label>
                        {{ linha.horafimantigo }}
                    {% endif %}
                    <hr>
                {% endfor %}
              </div>
              
            {% csrf_token %}
            <input type="hidden" v-bind:name="'linha_set-TOTAL_FORMS'" v-bind:id="'id_linha_set-TOTAL_FORMS'" v-model="this.linhas.length"/>
            <input type="hidden" v-bind:name="'linha_set-INITIAL_FORMS'" v-bind:id="'id_linha_set-INITIAL_FORMS'" v-model="this.start"/>
            <div style="margin-top: 2%; text-align: center; position: center">
                <button type="button" value="Voltar" class="button is-outlined" style="margin-right: 5%" onclick="voltar()">
                    Voltar
                </button>
                <button type="submit" class="button is-success is-outlined" name="Submit">
                    <span>Confirmar</span>
                </button>
            </div>
    </div>
</body>

{% endblock content %} {% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    function voltar() {
        location.href = "/pedidoSala";
    }
</script>
{% endblock scripts %}