GestaoPedidos/pedidosUC/urls.py
from django.urls import path
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
#router.register('pedidos', test_api)


app_name = 'pedidosUC'
urlpatterns = [
    path('',views.index, name = "pedido_uc"),
    path('criar-pedido/', views.criar_pedido, name='criar_pedido_uc'),
    path('editar-pedido/<int:pedido_id>', views.editar_pedido, name='editar_pedido_uc'),
    path('eliminar-pedido/<int:pedido_id>', views.eliminar_pedido_uc, name='eliminar_pedido_uc'),
    path('view-pedido/<int:pedido_id>', views.view_pedido, name='view_pedido_uc'),
    path('alterar-estado-pedido/<int:pedido_id>', views.alterar_estado_pedido_uc, name='alterar_estado_pedido_uc'),
    path('sucesso/',views.sucesso, name = "sucesso"),
]

GestaoPedidos/urls.py
from django.contrib import admin
from django.urls import path,include
from pedidos import urls as pedidos_urls
from pedidosUC import urls as pedidos_uc_urls
from pedidosHorario import urls as pedidos_horario_urls
from pedidosSala import urls as pedidos_sala_urls
from pedidosOutros import urls as pedidos_outros_urls
from custom_users import urls as users

urlpatterns = [
    path('pedidos/', include(pedidos_urls)),
    path('pedidoHorario/', include(pedidos_horario_urls)),
    path('pedidoUC/', include(pedidos_uc_urls)),
    path('pedidoSala/', include(pedidos_sala_urls)),
    path('pedidoOutros/', include(pedidos_outros_urls)),
    path('users/',include(users)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

GestaoPedidos/pedidos/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.contrib.auth.models import User
from django.db import models
from model_utils.managers import InheritanceManager

from custom_users.models import Docente, Funcionario


class AnoLetivo(models.Model):
    ano = models.CharField(db_column='Ano', max_length=255, blank=True, null=True) 
    datainicio = models.DateField(db_column='DataInicio', blank=True, null=True)
    datafim = models.DateField(db_column='DataFim', blank=True, null=True)
    estado = models.CharField(db_column='Estado', max_length=255, blank=True, null=True) 
    class Meta:
        db_table = 'AnoLetivo'

class Curso(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    curso = models.CharField(db_column='curso', max_length=255, blank=True, null=True)
    codigo = models.IntegerField(db_column='Codigo', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'Curso'


class Semestre(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    inicio_data = models.DateField(db_column='Inicio_Data', blank=True, null=True)  # Field name made lowercase.
    fim_data = models.DateField(db_column='Fim_Data', blank=True, null=True)  # Field name made lowercase.
    nr_horas_service = models.IntegerField(db_column='Nr_Horas_service', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'Semestre'

class Disciplina(models.Model):
    id = models.AutoField(db_column='ID2', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    estado = models.TextField(db_column='Estado')  # Field name made lowercase. This field type is a guess.
    codigodisciplina = models.IntegerField(db_column='codigodisciplina', blank=True, null=True)  # Field name made lowercase.
    semestreid = models.ForeignKey(Semestre, on_delete=models.CASCADE, db_column='SemestreID')  # Field name made lowercase.
    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'Disciplina'

class CursoDisciplina(models.Model):
    cursoid = models.OneToOneField(Curso, on_delete=models.CASCADE, db_column='CursoID', primary_key=True)  # Field name made lowercase.
    disciplinaid2 = models.ForeignKey(Disciplina, on_delete=models.CASCADE, db_column='DisciplinaID2')  # Field name made lowercase.

    class Meta:
        db_table = 'Curso_Disciplina'
        unique_together = (('cursoid', 'disciplinaid2'),)





class Turma(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nturma = models.CharField(db_column='NTurma', max_length=255, blank=True, null=True)  # Field name made lowercase.
    horas_semanais = models.CharField(db_column='Horas_semanais', max_length=255, blank=True, null=True)  # Field name made lowercase.
    horas_periodo = models.CharField(db_column='Horas_periodo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    class Meta:
        db_table = 'Turma'



class Instituicao(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    sigla = models.CharField(db_column='Sigla', max_length=255, blank=True, null=True)
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'Instituicao'


class Edificio(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)
    instituicao = models.ManyToManyField(Instituicao, through='EdificioInstituicao', related_name='edificios')
    localizacao = models.CharField(db_column='Localizacao', max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'Edificio'



class EdificioInstituicao(models.Model):
    edificio = models.ForeignKey(Edificio, on_delete=models.CASCADE)
    instituicao = models.ForeignKey(Instituicao, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Edificio_Instituicao'


class TipoSala(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    tipo = models.CharField(db_column='Tipo', max_length=255, null=False)
    
    class Meta:
        db_table = 'TipoSala'

class Sala(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nsala = models.CharField(db_column='NSala', max_length=255, blank=True, null=True)  # Field name made lowercase.
    lotacao = models.IntegerField(db_column='Lotacao', blank=True, null=True)  # Field name made lowercase.
    tipo_sala = models.ManyToManyField(TipoSala)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)
    edificioid = models.ForeignKey(Edificio, on_delete=models.CASCADE, db_column='EdificioID', null=True)  # Field name made lowercase.
    anoletivo = models.ForeignKey(AnoLetivo, on_delete=models.CASCADE, db_column='AnoLetivo', null=True) # Field name made lowercase.
    
    class Meta:
        db_table = 'Sala'

class Docentes(models.Model):
    # Add any additional fields specific to Docente model here
    codigo = models.IntegerField(db_column='Codigo', blank=True,primary_key=True,default=0)  # Field name made lowercase.
    ativo = models.CharField(db_column='Ativo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    individuo = models.CharField(db_column='Individuo',max_length=255,blank=True, null=True)  # Field name made lowercase.
    data_de_nascimento = models.CharField(db_column='data_de_nascimento', max_length=255,blank=True, null=True)  # Field name made lowercase.
    sexo = models.CharField(db_column='sexo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    tipo_de_identificacao = models.CharField(db_column='tipo_de_Identificacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    identificacao = models.CharField(db_column='identificacao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    data_de_emissao_de_idenficacao = models.CharField(db_column='data_de_emissao_de_idenficacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nacionalidade = models.CharField(db_column='nacionalidade', max_length=255,blank=True, null=True)  # Field name made lowercase.
    arquivo = models.CharField(db_column='arquivo', max_length=255,blank=True, null=True)  # Field name made lowercase.
    data_de_validade_da_identificacao = models.CharField(db_column='data_de_validade_da_identificacao', max_length=255,blank=True, null=True)  # Field name made lowercase.
    nif = models.CharField(db_column='nif', max_length=255,blank=True, null=True)  # Field name made lowercase.
    pais_fiscal = models.CharField(db_column='pais_fiscal', max_length=255,blank=True, null=True)  # Field name made lowercase.
    digito_verificacao = models.CharField(db_column='digito_verificacao',max_length=255,blank=True, null=True)  # Field name made lowercase. This field type is a guess.

    class Meta:
        db_table = 'docentes'

class Pedido(models.Model):
    objects = InheritanceManager()
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nrpedido = models.IntegerField(db_column='NrPedido', blank=True, null=True)  # Field name made lowercase.
    titulo = models.CharField(db_column='titulo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    dataalvo = models.DateField(db_column='DataAlvo', blank=True, null=True)  # Field name made lowercase.
    dataanalise = models.DateField(db_column='DataAnalise', blank=True, null=True)  # Field name made lowercase.
    datavalidacao = models.DateField(db_column='DataValidacao', blank=True, null=True)  # Field name made lowercase.
    datacriacao = models.DateTimeField(db_column='DataCriacao', auto_now_add=True, blank=True, null=True)  # Field name made lowercase.
    estado = models.CharField(db_column='Estado', max_length=255, blank=True, null=True)  # Field name made lowercase.
    dataalteracao = models.DateTimeField(db_column='DataAlteracao', auto_now=True, blank=True, null=True)  # Field name made lowercase.
    anoletivo = models.ForeignKey(AnoLetivo, on_delete=models.CASCADE, db_column='AnoLetivo', null=True) 
    docente = models.ForeignKey(Docente, on_delete=models.SET_NULL, db_column='Docente', null=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.SET_NULL, db_column='Funcionario', null=True)
    class Meta:
        db_table = 'Pedido'



class Linha(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    uc = models.ForeignKey(Disciplina, on_delete=models.CASCADE, db_column='Disciplina', blank=False)#
    pedidoID = models.ForeignKey(Pedido, on_delete=models.CASCADE, db_column='PedidoID')#


class LinhaOutros(models.Model):

GestaoPedidos/pedidosUC/models.py
from django.db import models
from pedidos.models import *
# Create your models here.

class PedidoUC(Pedido):
   # tipopedido = models.ForeignKey(TipoPedido, on_delete=models.CASCADE, db_column='tipoPedidoID')  # Field name made lowercase.
    class Meta:
        db_table = 'PedidoUC'

GestaoPedidos/pedidosUC/forms.py
from django.forms import ModelForm
from django import forms
from .models import PedidoUC,Pedido
from pedidos.models import Disciplina, Linha
from datetime import datetime
from django.forms import inlineformset_factory


class PedidosDisciplinaForm(forms.ModelForm):
    class Meta:
        model = PedidoUC
        fields = ['titulo','descricao','dataalvo','anoletivo']


class LinhaForm(forms.ModelForm):
    class Meta:
        model = Linha
        fields = ['descricao','uc']

LinhaFormSet = inlineformset_factory(
    PedidoUC, Linha, LinhaForm, extra=0
)

GestaoPedidos/pedidosUC/templates/pedidosUC/bulma_table.html
{% load django_tables2 %}
{% load i18n %}
{% load static %}

{% block table-wrapper %}
{% block table %}
<div class="table-wrapper">
    <table
        class="main-table table has-mobile-cards is-fullwidth is-striped {% block table_class %}{% endblock table_class %}"
        {% if table.fixed %}style="table-layout: fixed;" {% endif %} {% render_attrs table.attrs %}>

        <!-- Colum bar-->
        {% block table.thead %}
        {% if table.show_header %}
        <thead {{ table.attrs.thead.as_html }}>
            <tr>
                {% block seta_th %}
                {% endblock seta_th %}
                {% for column in table.columns %}
                <th {% if column.orderable %}
                        class="orderable {% if request.GET.sort == column.order_by_alias %}is-sorting{% endif %}" 
                    {% endif %}
                    {% if column.orderable %}
                        onclick="window.location.href = '{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}';"
                    {% endif %} {{ column.attrs.th.as_html }}
                >
                    {% if column.attrs.abbr %}<abbr title="{{column.attrs.abbr.title}}">
                    {% endif %}
                    {{ column.header }}
                    {% if column.attrs.abbr %}</abbr>
                    {% endif %}
                    {% if column.orderable and request.GET.sort == column.order_by_alias %}
                        {% if column.order_by_alias|slice:"0:1" == "-" %}
                            <span class="icon is-small"><i class="mdi mdi-menu-up"></i></span>
                        {% else %}
                            <span class="icon is-small"><i class="mdi mdi-menu-down"></i></span>
                        {% endif %}
                    {% endif %}
                </th>
                {% endfor %}
                <th>
                    Operações
                </th>
            </tr>
            
        </thead>
        {% endif %}
        {% endblock table.thead %}
        

        <!-- Body-->
        {% block table.tbody %}
        <tbody {{ table.attrs.tbody.as_html }}>
            {% for row in table.paginated_rows %}
            {% block table.tbody.row %}
            <tr {{ row.attrs.as_html }}  style="word-wrap: break-word;">
                {% block seta_tr %}
                {% endblock seta_tr %}
                {% for column, cell in row.items %}
                <td {{ column.attrs.td.as_html }} data-label="{{column.header}}">
                    {% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}
                </td>
                {% endfor %}
                <td>
                    <div>
                    <span class='icon'></span>
                    <a href="{% url 'pedidosUC:view_pedido_uc' row.record.id %}"><img src="{% static 'img/view.png' %}" width="20px" height="20px"></a>
                    {% if user.is_docente %}
                        {% if row.record.estado == "espera" %}
                            <a href="{% url 'pedidosUC:editar_pedido_uc' row.record.id %}"><img src="{% static 'img/edit.png' %}" width="20px" height="20px"></a>
                            <a href="{% url 'pedidosUC:eliminar_pedido_uc' row.record.id %}" title="Mudar estado para analise" onclick="return confirm('Tem a certeza?')"><img title="hover text" src="{% static 'img/delete.png' %}" width="20px" height="20px"></a>
                        {% endif %}
                    {% endif %}

                    </div>
                </td>
            </tr>
            {% endblock table.tbody.row %}

            {% block detail %}
            {% endblock detail %}

            {% empty %}
            {% if table.empty_text %}
            {% block table.tbody.empty_text %}
            <tr>
                <td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td>
            </tr>
            {% endblock table.tbody.empty_text %}
            {% endif %}
            {% endfor %}
        </tbody>
        {% endblock table.tbody %}


        {% block table.tfoot %}
        {% if table.has_footer %}
        <tfoot {{ table.attrs.tfoot.as_html }}>
            <tr>
                {% for column in table.columns %}
                <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
            </tr>
        </tfoot>
        {% endif %}
        {% endblock table.tfoot %}


    </table>
</div>
{% endblock table %}

<!-- Pagination-->
{% block pagination %}
<div class="level">
    <div class="level-left"></div>
    <div class="level-right">
        <div class="level-item">
            <nav class="pagination" role="navigation" aria-label="pagination">
                {% block pagination.range %}
                {% for p in table.page|table_page_range:table.paginator %}
                <ul class="pagination-list">
                    <li>
                        {% if p == table.page.number %}
                        <a class="pagination-link is-current" href="">{{ p }}</a>
                        {% elif p == '...' %}
                        <span class="pagination-ellipsis">&hellip;</span>
                        {% else %}
                        <a class="pagination-link" href="{% querystring table.prefixed_page_field=p %}">
                            {{ p }}
                        </a>
                        {% endif %}
                    </li>
                </ul>
                {% endfor %}
                {% endblock pagination.range %}
                {% block pagination.previous %}
                <a role="button" {% if table.page.has_previous %}
                    href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" {% else %}
                    disabled="disabled" {% endif %} class="pagination-previous"><span class="icon" aria-hidden="true"><i
                            class="mdi mdi-chevron-left mdi-24px"></i></span></a>
                {% endblock pagination.previous %}
                {% block pagination.next %}
                <a role="button" {% if table.page.has_next %}
                    href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" {% else %}
                    disabled="disabled" {% endif %} class="pagination-next"><span class="icon" aria-hidden="true"><i
                            class="mdi mdi-chevron-right mdi-24px"></i></span></a>
                {% endblock pagination.next %}
            </nav>
        </div>
    </div>
</div>
{% endblock pagination %}
{% block scripts %}
{% endblock scripts %}
{% endblock table-wrapper %}

<head>
    <style>
        .icon {
            background: url('your-image-url.jpg');
            height: 20px;
            width: 20px;
            display: block;
            /* Other styles here */
        }
        th.orderable {
            cursor: pointer;
        }

        th.orderable:hover {
            border-color: #7a7a7a;
        }

        th.orderable.is-sorting {
            border-color: #7a7a7a;
        }

        .table-wrapper .table {
            margin-bottom: 0
        }

        .table-wrapper:not(:last-child) {
            margin-bottom: 1.5rem
        }

        @media screen and (max-width:1023px) {
            .table-wrapper {
                overflow-x: auto
            }
        }

        @media screen and (max-width:768px) {
            .table.has-mobile-cards thead {
                display: none
            }

            .table.has-mobile-cards tfoot th {
                border: 0;
                display: inherit
            }

            .table.has-mobile-cards tr {
                -webkit-box-shadow: 0 2px 3px rgba(10, 10, 10, .1), 0 0 0 1px rgba(10, 10, 10, .1);
                box-shadow: 0 2px 3px rgba(10, 10, 10, .1), 0 0 0 1px rgba(10, 10, 10, .1);
                max-width: 100%;
                position: relative;
                display: block
            }

            .table.has-mobile-cards tr td {
                border: 0;
                display: inherit
            }

            .table.has-mobile-cards tr td:last-child {
                border-bottom: 0
            }

            .table.has-mobile-cards tr:not(:last-child) {
                margin-bottom: 1rem
            }

            .table.has-mobile-cards tr:not([class*=is-]) {
                background: inherit
            }

            .table.has-mobile-cards tr:not([class*=is-]):hover {
                background-color: inherit
            }

            .table.has-mobile-cards tr.detail {
                margin-top: -1rem
            }

            .table.has-mobile-cards tr:not(.detail):not(.is-empty):not(.table-footer) td {
                display: -webkit-box;
                display: -ms-flexbox;
                display: flex;
                width: auto;
                -webkit-box-pack: justify;
                -ms-flex-pack: justify;
                justify-content: space-between;
                text-align: right;
                border-bottom: 1px solid #f5f5f5
            }

            .table.has-mobile-cards tr:not(.detail):not(.is-empty):not(.table-footer) td:before {
                content: attr(data-label);
                font-weight: 600;
                padding-right: .5em;
                text-align: left
            }
        }
    </style>
    {% block style %}
    {% endblock style %}
    <script>
    const select = document.getElementById('estado-select');

    select.addEventListener('change', () => {
        const selectedOption = select.value;
        console.log(selectedOption);
    });


    function showSaveButton(selectElement) {
        var selectedOptionValue = selectElement.value;
        var rowId = selectElement.id.split('-')[2];
        var submitButton = document.getElementById('submit-btn-' + rowId);
        if (selectedOptionValue === '{{ row.record.estado }}') {
            submitButton.style.display = 'none';
        } else {
            submitButton.style.display = 'inline';
        }
    }
</script>
</head>

GestaoPedidos/pedidosUC/templates/pedidosUC/index_uc.html
{% extends 'app.html' %}
{% load django_tables2 %}
{% load static %}

{% block title %}- Consultar Utilizadores
{% endblock title %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    setTimeout(function() {
        $('#mensagem').fadeOut('fast');
    }, 5000); // Tempo de exibição em milissegundos
});
</script>
{% if mensagem %}
<div id="mensagem">
    <div class="mensagem" style="text-align:center; background-color:{{ colorBack }}; color:{{ color }}; padding:20px; display:block;">
        <h2>{{ mensagem }}</h2>
    </div>
    <br>
</div>
{% endif %}
    <div class="columns">
        <div class="column is-3">
            <div class="menu">
                <div class="menu-label">
                    Filtros Pedidos de Disciplina
                </div>
                <form action="{% url 'pedidosUC:pedido_uc' %}" method="GET">
                    <ul class="menu-list">
                        <li>
                            <div class="field">
                                <div class="control has-icons-left">
                                    <input class="input" name="pesquisa"
                                           {% if name %}value="{{name}}"{% else %}value="{{ filter.form.nome.value|default_if_none:'' }}"{% endif %} type="text"
                                           placeholder="Informação" >
                                    <span class="icon is-left">
                                    <i class="mdi mdi-magnify mdi-24px"></i>
                                </span>
                                </div>
                            </div>
                            <div class="field">
                                <label>Tipos:
                                    <br>
                                    <input type="checkbox" name="opcao" value="Titulo">Titulo <br>
                                    <input type="checkbox" name="opcao" value="Descricao"> Descrição <br>
                                    <input type="checkbox" name="opcao" value="Estado"> Estado <br>
                                    <input type="checkbox" name="opcao" value="ID"> ID <br>
                                </label>
                            </div>

                            <div class="field">
                                <label for="id_estado">Estado:</label><br>
                                <select name="id_estado" id="id_estado" class="button is-info">
                                    <option value="todos" >Todos</option>
                                    <option value="espera" {% if 'espera' in id_estado %}selected{% endif %}>Espera</option>
                                    <option value="analise" {% if 'analise' in id_estado %}selected{% endif %}>Análise</option>
                                    <option value="validado" {% if 'validado' in id_estado %}selected{% endif %}>Validado</option>
                                    <option value="recusado" {% if 'recusado' in id_estado %}selected{% endif %}>Recusado</option>
                                </select>
                            </div>

                            <ul>
                                {% for value, label in filter.form.fields.groups.choices %}
                                    <div class="field" style="padding-left: 1rem;">
                                        <label class="checkbox">
                                            <input type="checkbox" name="{{ filter.form.groups.name }}"
                                                   value="{{ value|stringformat:'s' }}"
                                                   {% if value|stringformat:'s' in filter.form.groups.value %}checked{% endif %}>
                                            {% if label == "ProfessorUniversitario" %}Professor
                                                Univesitário{% else %}{{ label }}{% endif %}
                                        </label>
                                    </div>
                                {% endfor %}
                            </ul>
                        </li>
                        <li>
                            <ul>
                                {% for value, label in filter.form.fields.valido.choices %}
                                    <div class="field" style="padding-left: 1rem;">
                                        <label class="checkbox">
                                            <input type="checkbox" name="{{ filter.form.valido.name }}"
                                                   value="{{ value|stringformat:'s' }}"
                                                   {% if value|stringformat:'s' in filter.form.valido.value %}checked{% endif %}>
                                            {{ label }}
                                        </label>
                                    </div>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <div class="field is-grouped">
                        <p class="control is-expanded">
                            <input class="button is-light is-fullwidth" type="reset"
                                   onclick="event.preventDefault(); window.location='{% url 'pedidosUC:pedido_uc' %}';"
                                   value="Limpar">
                        </p>
                        <p class="control is-expanded">
                            <button class="button is-primary is-fullwidth" type="submit">
                            <span class="icon">
                                <i class="mdi mdi-magnify"></i>
                            </span>
                                <span>Pesquisar</span>
                            </button>
                        </p>
                    </div>
                </form>
            </div>
        </div>
        <div class="column">
            <nav aria-label="breadcrumbs" class="breadcrumb">
                <ul>
                    <li><a href="">Início</a></li>
                    <li class="is-active"><a href="">Pedidos de Disciplina</a>
                    </li>
                </ul>
            </nav>
            <a href="{% url 'pedidosUC:criar_pedido_uc' %}">
                <button type="button" class="button is-success is-outlined" style="margin-bottom: 1rem;"><span
                        class="icon is-small"><i class="mdi mdi-plus"></i></span> <span>Criar Pedidos de Disciplina</span>
                </button>
            </a>
            <!--

            <ul>
                {% for pedido in pedidos %}
                    <li>{{ pedido.titulo }} <a href="{% url 'pedidosUC:eliminar_pedido_uc' pedido.id %}">Delete</a> <a href="{% url 'pedidosUC:editar_pedido_uc' pedido.id %}">Edit</a></li>
                {% endfor %}
                {% render_table table 'django_tables2/semantic.html' %}
            </ul> -->
            {% render_table table %}

        </div>
    </div>
{% endblock content %}

GestaoPedidos/pedidosUC/templates/pedidosUC/index_uc_tabela.html
{% extends 'pedidosUC/bulma_table_details.html' %}

{% block details_content %}

<table style="
    width: 100%;
    table-layout: fixed;
">
    <tbody style="table-layout: fixed;">
        {% for l in row.record.linha_set.all %}
            <tr>
                <td 
                style="width:15%; max-width:100px;
                            overflow: hidden;
                            text-overflow: ellipsis;
                            white-space: nowrap;"
                >
                    <b>Titulo:</b> {{l.titulo}}
                </td>
                
                <td 
                style="width:15%; max-width:100px;
                            overflow: hidden;
                            text-overflow: ellipsis;
                            white-space: nowrap;"
                >
                    <b>Descrição:</b> {{l.descricao}}
                </td>

                <td style="width:15%; max-width:100px;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;"
                >
                    <b>Unidade Curricular:</b> {{l.uc.nome}}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock details_content %}

GestaoPedidos/pedidosUC/templates/pedidosUC/success.html
{% extends 'app.html' %}
{% load django_tables2 %}
{% load static %}

{% block title %}- Consultar Utilizadores
{% endblock title %}

{% block content %}
    <div class="columns">
        <div class="column">
            <nav aria-label="breadcrumbs" class="breadcrumb">
                <ul>
                    <li><a href="{% url 'pedidosUC:pedido_uc' %}">Início</a></li>
                    <li class="is-active"><a href="">Pedidos de Disciplina</a>
                    </li>
                </ul>
            </nav>
            <div>
                {{mensagem}}
            </div>
        </div>
    </div>
{% endblock content %}